version: '3.8'
networks:
  app_network:
    driver: bridge

services:
  frontend:
    image: node:18
    command: sh -c "npx create-react-app my-app && cd my-app && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
    networks:
      - app_network

  backend:
    image: node:18
    command: sh -c "npm install express mysql && node server.js"
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=emp_details
    restart: always
    networks:
      - app_network
    
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emp_details
    restart: always
    networks:
      - app_network